[package]
name = "rdtscp-test"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]

[dependencies]
[profile.release]
opt-level = 3
rpath = true
debug = true
debug-assertions = false
